-- Snowflake load entry points. Run after creating snowflake/ddl/canonical_model.sql.
-- Paths are deliberately parameterised for the deployment stage.
COPY INTO CANONICAL.RAW_PLCYMSTR (RAW_RECORD, SOURCE_FILE)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @CANONICAL_LEGACY_STAGE/PLCYMSTR_D260115.dat
)
FILE_FORMAT = (FORMAT_NAME = CANONICAL.FF_FIXED_WIDTH_PLCYMSTR);

COPY INTO CANONICAL.RAW_POLMSTEX (RAW_RECORD, SOURCE_FILE)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @CANONICAL_LEGACY_STAGE/POLMSTEX_D260115.dat
)
FILE_FORMAT = (FORMAT_NAME = CANONICAL.FF_FIXED_WIDTH_POLMSTEX);

COPY INTO CANONICAL.RAW_BDX_CLAIMS
  (BORDEREAU_REF, POLICY_REFERENCE, INSURED_NAME, DATE_OF_LOSS, PERIL,
   EST_INCURRED_GBP, PAID_TO_DATE_GBP, STATUS, UMR, SOURCE_FILE)
FROM (
  SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, METADATA$FILENAME
  FROM @CANONICAL_LEGACY_STAGE/CLAIMS_BDX_BRK0007_202606.csv
)
FILE_FORMAT = (FORMAT_NAME = CANONICAL.FF_BDX_CSV)
ON_ERROR = 'CONTINUE';

-- Quarantined rows are retained for DQR-030/DQR-041 reconciliation.
COPY INTO CANONICAL.REJECT
FROM @CANONICAL_LEGACY_STAGE/rejects/
FILE_FORMAT = (FORMAT_NAME = CANONICAL.FF_REJECT_CSV);
