CREATE SCHEMA IF NOT EXISTS CANONICAL;

CREATE OR REPLACE FILE FORMAT CANONICAL.FF_FIXED_WIDTH_PLCYMSTR
  TYPE = CSV FIELD_DELIMITER = NONE RECORD_DELIMITER = '\n' SKIP_HEADER = 0;
CREATE OR REPLACE FILE FORMAT CANONICAL.FF_FIXED_WIDTH_POLMSTEX
  TYPE = CSV FIELD_DELIMITER = NONE RECORD_DELIMITER = '\n' SKIP_HEADER = 0;
CREATE OR REPLACE FILE FORMAT CANONICAL.FF_BDX_CSV
  TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1;
CREATE OR REPLACE FILE FORMAT CANONICAL.FF_REJECT_CSV
  TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1;

CREATE OR REPLACE TABLE CANONICAL.PARTY (
  PARTY_ID VARCHAR(8) NOT NULL,
  PARTY_TYPE VARCHAR(6),
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  BIRTH_DT DATE,
  NINO_HASH VARCHAR(128),
  EMAIL_ADDR VARCHAR(120),
  PHONE VARCHAR(20),
  ADDR_LINE1 VARCHAR(120),
  CITY VARCHAR(60),
  POSTCODE VARCHAR(10),
  LEGACY_CUSTOMER_ID NUMBER(10,0),
  MDM_GOLDEN_FLAG VARCHAR(1),
  CREATE_DT DATE,
  CONSTRAINT PK_PARTY PRIMARY KEY (PARTY_ID)
);

CREATE OR REPLACE TABLE CANONICAL.XREF_CLIENT_PARTY (
  CLIENT_NO NUMBER(10,0) NOT NULL,
  PARTY_ID VARCHAR(8),
  MATCH_METHOD VARCHAR(20),
  MATCH_CONFIDENCE NUMBER(3,2),
  LOADED_BY VARCHAR(30),
  LOAD_DT DATE,
  CONSTRAINT PK_XREF_CLIENT_PARTY PRIMARY KEY (CLIENT_NO)
);

CREATE OR REPLACE TABLE CANONICAL.POLICY (
  POLICY_ID VARCHAR(18) NOT NULL,
  LEGACY_POLICY_NO VARCHAR(18) NOT NULL,
  PARTY_ID VARCHAR(8),
  PRODUCT_CODE VARCHAR(4),
  INCEPTION_DATE DATE,
  EXPIRY_DATE DATE,
  STATUS VARCHAR(9) NOT NULL CHECK (STATUS IN ('ACTIVE','LAPSED','CANCELLED','EXPIRED')),
  ANNUAL_PREMIUM_GBP NUMBER(15,2),
  EARNED_PREMIUM_GBP NUMBER(15,2),
  POSTCODE VARCHAR(10),
  POSTCODE_DQ_STATUS VARCHAR(7) NOT NULL CHECK (POSTCODE_DQ_STATUS IN ('VALID','INVALID','MISSING')),
  BROKER_ID VARCHAR(7),
  SOURCE_SYSTEM VARCHAR(9) NOT NULL CHECK (SOURCE_SYSTEM IN ('PLCYMSTR','LIFE400','GUIDEWIRE')),
  CONSTRAINT PK_POLICY PRIMARY KEY (POLICY_ID)
);

CREATE OR REPLACE TABLE CANONICAL.CLAIM (
  CLAIM_ID VARCHAR(20) NOT NULL,
  POLICY_ID VARCHAR(18) NOT NULL,
  LOSS_DATE DATE NOT NULL,
  NOTIFIED_DATE DATE,
  STATUS VARCHAR(8) NOT NULL CHECK (STATUS IN ('OPEN','CLOSED','REOPENED','DECLINED')),
  INCURRED_GBP NUMBER(15,2),
  PAID_GBP NUMBER(15,2),
  FRAUD_FLAG VARCHAR(9) NOT NULL CHECK (FRAUD_FLAG IN ('Y','N','SUSPECTED')),
  SOURCE_SYSTEM VARCHAR(9) NOT NULL CHECK (SOURCE_SYSTEM IN ('PLCYMSTR','LIFE400','GUIDEWIRE'))
);

CREATE OR REPLACE TABLE CANONICAL.REJECT (
  FEED VARCHAR(128) NOT NULL,
  LINE_NUMBER NUMBER,
  REASON VARCHAR(255) NOT NULL,
  RAW_RECORD VARCHAR(4096),
  REJECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CANONICAL.DQ_PASS_RATES (
  RULE_ID VARCHAR(7) NOT NULL,
  PASS_RATE NUMBER(5,4) NOT NULL,
  EVALUATED_ROWS NUMBER,
  FAILED_ROWS NUMBER,
  METHOD VARCHAR(255)
);

CREATE OR REPLACE TABLE CANONICAL.RAW_PLCYMSTR (
  RAW_RECORD VARCHAR(4096),
  SOURCE_FILE VARCHAR(512),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CANONICAL.RAW_POLMSTEX (
  RAW_RECORD VARCHAR(4096),
  SOURCE_FILE VARCHAR(512),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CANONICAL.RAW_BDX_CLAIMS (
  BORDEREAU_REF VARCHAR,
  POLICY_REFERENCE VARCHAR,
  INSURED_NAME VARCHAR,
  DATE_OF_LOSS VARCHAR,
  PERIL VARCHAR,
  EST_INCURRED_GBP VARCHAR,
  PAID_TO_DATE_GBP VARCHAR,
  STATUS VARCHAR,
  UMR VARCHAR,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
